// Created 6/16/2014 12:31:41 PM
(function(){var c=function b(){if(2===arguments.length&&"number"===typeof arguments[0]&&"number"===typeof arguments[1])this.x=arguments[0],this.y=arguments[1];else if(1===arguments.length&&arguments[0].type===b.type)this.x=arguments[0].x,this.y=arguments[0].y;else if(0===arguments.length)this.y=this.x=0;else throw"Arguments must be 2 numbers or nothing at all";},d=c.prototype;c.type="Vector2";d.type=c.type;d.set=function(b,a){if(2===arguments.length&&"number"===typeof arguments[0]&&"number"===typeof arguments[1])this.x=
arguments[0],this.y=arguments[1];else if(1===arguments.length&&arguments[0].type===c.type)this.x=arguments[0].x,this.y=arguments[0].y;else throw'Argument must be 2 numbers or 1 "Vector2"';};d.neg=function(){return new c(-this.x,-this.y)};d.vclone=function(){return new c(this.x,this.y)};d.add=function(b){var a=new c(this.x,this.y);if("number"===typeof b)a.x+=b,a.y+=b;else if(b.type&&b.type===c.type)a.x+=b.x,a.y+=b.y;else throw'Argument must be of type "Vector2" or "number"';return a};d.sub=function(b){var a=
new c(this.x,this.y);if("number"===typeof b)a.x-=b,a.y-=b;else if(b.type&&b.type===c.type)a.x-=b.x,a.y-=b.y;else throw'Argument must be of type "Vector2" or "number"';return a};d.mul=function(b){var a=new c(this.x,this.y);if("number"===typeof b)a.x*=b,a.y*=b;else if(b.type&&b.type===c.type)a.x*=b.x,a.y*=b.y;else throw'Argument must be of type "Vector2" or "number"';return a};d.div=function(b){var a=new c(this.x,this.y);if("number"===typeof b)a.x/=b,a.y/=b;else if(b.type&&b.type===c.type)a.x/=b.x,
a.y/=b.y;else throw'Argument must be of type "Vector2" or "number"';return a};d.dot=function(b){if(!b||!b.type||b.type!==c.type)throw'Arguments must be of type "Vector2"';return this.x*b.x+this.y*b.y};d.square=function(){return new c(this.x*this.x,this.y*this.y)};d.vlength=function(){return Math.sqrt(this.x*this.x+this.y*this.y)};d.abs=function(){return new c(Math.abs(this.x),Math.abs(this.y))};d.proportions=function(){return this.x/this.y};d.map=function(b){var a=new c;a.x=b(this.x);a.y=b(this.y);
return a};c.dot=function(b,a){if(b.type!==c.type||a.type!==c.type)throw'Arguments must be of type "Vector2"';return b.x*a.x+b.y*a.y};c.crossVV=function(b,a){if(b.type!==c.type||a.type!==c.type)throw'Arguments must be of type "Vector2"';return b.x*a.y-b.y*a.x};c.crossVN=function(b,a){if(b.type!==c.type||"number"!==typeof a)throw'Arguments must be of type "Vector2" and "number"';return new c(a*b.y,-a*b.x)};c.crossNV=function(b,a){if("number"!==typeof b||a.type!==c.type)throw'Arguments must be of type "number" and "Vector2"';
return new c(-b*a.y,b*a.x)};d.clip=function(b,a,d,k){var g=new c;g.x=Math.max(b,Math.min(d,this.x));g.y=Math.max(a,Math.min(k,this.y));return g};d.toString=function(){return"("+this.x+","+this.y+")"};window.Vector2=c;d.applyAsPosition=function(b,a,c){b.style["undefined"===typeof a||a?"left":"right"]=this.x+"px";b.style["undefined"===typeof c||c?"top":"bottom"]=this.y+"px"};d.applyAsSize=function(b){b.style.width=this.x+"px";b.style.height=this.y+"px"};d.applyAsMargin=function(b,a,c){var d=function(a,
b,c,d,l,q){"undefined"===typeof c||null===c?(a.style[b+d]=q+"px",a.style[b+l]=q+"px"):a.style[b+(c?d:l)]=q+"px"};d(b,"margin",a,"Left","Right",this.x);d(b,"margin",c,"Top","Bottom",this.y)};d.stretchToMe=function(b,a){var d=new c;d.x=Math[a?"min":"max"](this.x,b*this.y);d.y=d.x/b;return d};d.getCenterPosition=function(b){return this.sub(b).div(2)}})();function setElementPosition(c,d){c.style.left=String(d.left).concat("px");c.style.top=String(d.top).concat("px")}
function flipPage(c){c?pageMediator.right():pageMediator.left()}function hidePreloader(){window.preloaderIsShown&&(workspace.preloader.del(),window.preloaderIsShown=!1)}function showPreloader(){window.preloaderIsShown||(window.preloaderIsShown=!0,workspace.preloader.add())}function dev_rotateXY(c){return"rotate("+c.toString()+"rad)"}function deleteAllChildren(c){for(;c.firstChild;)c.removeChild(c.firstChild)}
function sizeDiv(c,d,e,b){void 0==d&&void 0==e&&(d=window.innerWidth,e=window.innerHeight);c.style.width=b?d+"%":Math.ceil(d)+"px";c.style.height=b?e+"%":Math.ceil(e)+"px"}function px(c){return c.toString()+"px"}
function parseVectorizedContentToDiv(c,d,e,b){b="undefined"!=typeof b?b:!0;for(var a=0;4>a;a++);d=d||createDiv();for(var a=[],l=0;l<c.length;l++){var k=c[l],g=0,h=k[g++].toString(),r=k[g++].toString(),s=parseFloat(k[g++]);parseFloat(k[g++]);var x=parseFloat(k[g++]),q=parseFloat(k[g++]),m=parseFloat(k[g++]),n=k[g++].toString(),k=parseFloat(k[g++]),t=Math.round(q*e),g=q=document.createElement("p");g.style.position="absolute";g.style.whiteSpace="nowrap";q.innerText=h;q.style.fontFamily=r;g.style.top=
px(Math.round(x*e));g.style.left=px(t);r=m;x=a[r];m="undefined"==typeof x?Math.floor(m*e):x.size;q.style.fontSize=px(m);q.style.color=n;d.appendChild(g);s*=e;if(b)for(;q.offsetWidth>s&&1<m;)m-=1,q.style.fontSize=px(m);if("undefined"==typeof x)a[r]={size:m,elements:[q]};else if(x.size>=m){if(x.size>m){a[r].size=m;for(var y in x.elements)n=x.elements[y],m=n.offsetWidth,n.style.fontSize=px(a[r].size),n.style.wordSpacing="0px",n.style.wordSpacing=px((m-n.offsetWidth)/(n.innerText.split(" ").length-1))}a[r].elements.push(q)}q.style.webkitTransform=
k?dev_rotateXY(k):"";q.style.webkitTransformOrigin=k?"0 0":"";h=h.split(" ");q.style.wordSpacing="0px";q.style.wordSpacing=px((s-q.offsetWidth)/(h.length-1))}return d}function getDefaultMobileScaleMode(c,d,e,b){var a={};switch(c){case PT_CATALOG:case PT_MAGAZINE:a.isHalfPage=!d&&e;case PT_BOOK:case PT_DOCUMENT:a.fitMode=b?"screen":"width";break;case PT_PHOTOALBUM:a.fitMode="screen";break;default:throw"unknown publication type";}return a}
function getKeepZoomScaleWhileFlipping(c){return-1!=[PT_BOOK,PT_DOCUMENT].indexOf(c)}
function determineScaleMap(c,d){var e=getDefaultMobileScaleMode(publicationData.type,"tablet"==system.device.type,d,innerWidth<=innerHeight),b=e.isHalfPage?2:1,a=(new Vector2(innerWidth,innerHeight)).stretchToMe(c.x/b/c.y,!0).x/c.x,b=innerWidth/(c.x/b),l=b/0.8,e=["screen"==e.fitMode?a:b];ALBUM?(a=Math.sqrt(l/b),e=e.concat([b*a,l])):a=1.5;for(;e[e.length-1]*a<4*e[0];)e[e.length]=e[e.length-1]*a;return{defaultPos:0,map:e,textVisibleMaxPos:4}}var v=window.system.platform.version;
window.hasClearChildrenBug="safari"==window.system.browser.name&&fbUtils.isArray(v)&&2<=v.length&&"4"==v[0]&&2<=v[1];
function parseContentItems(c,d,e,b,a){if("undefined"!=typeof d&&d)for(var l=0,k=d.length;l<k;l++){var g=d[l],h={cart:publicationData.shopInfo?cart:null,searchHighlightColor:publicationData.visibility.search?highlight.getFillStyle():null,linkHighlightColor:publicationData.linkcolor,onInternalLinkClick:function(a){pageMediator.goToPage(parseInt(a))},getVideoImageUrl:function(a){return video.getVideoImageUrl(a)},videoPlayImage:video.getPlayImage(),onVideoClick:function(a){video.play(a.type,a.id,function(){system.platform.ios||
(window.resources.MAIN_FRAME.style.visibility="visible")});system.platform.ios||(window.resources.MAIN_FRAME.style.visibility="hidden")},formCartItemOptions:function(a,b){function c(a,b){return a.hasOwnProperty(b)?a[b]:publicationData.shopInfo.cartIconGlobals[b]}return{orientation:c(a,"position"),circleColor:c(a,"circleColor"),priceColor:c(a,"priceColor"),priceTagColor:c(a,"priceTagColor"),priceTagOpacity:c(a,"priceTagColorAlpha"),tagVisible:c(a,"tagVisible"),basketColor:c(a,"basketColor"),showTitle:c(a,
"showTitle"),cost:b.price,title:b.name,onClickAction:c(a,"onClickAction")}},onCartItemClick:function(a,b,c){a?(new ProductInfoWindow(b.id)).show():window.location.href=c.url},onNewCartItemRenderConstruction:function(a){window.cartRenders.push(a)}};parseContentItem(c,g,e,b,h,a)}}
function parseContentItem(c,d,e,b,a,l){var k=new Vector2(d.x,d.y),g=new Vector2(d.width,d.height),h=document.createElement("div");h.style.position="absolute";k=k.mul(b);g=g.mul(b);(function(a,b,c,d){a.style[HTML5lib.browserPrefix+"TransformOrigin"]="0 0";var e=d?Math.sin(d):0;d=d?Math.cos(d):1;a.style[HTML5lib.browserPrefix+"Transform"]="matrix("+[d,e,-e,d,b.x,b.y].join()+")";sizeDiv(a,c.x,c.y,!1)})(h,k,g,d.angle);"undefined"!=typeof d.zindex&&(h.style.zIndex=d.zindex);if("highlight"==c)h.style.backgroundColor=
a.searchHighlightColor,e.appendChild(h);else if("link"==c)h.style.backgroundColor=a.linkHighlightColor,h.style.opacity="0",h.style.webkitAnimation="linkss 2s",h.className="link",b=d.urls,Hammer(h,{prevent_default:!0,stop_browser_behavior:!0}).on("touch",function(){h.style.opacity="0.3"}),Hammer(h,{prevent_default:!0,stop_browser_behavior:!0}).on("drag transform hold release",function(){h.style.opacity="0"}),b&&0!=b.length?(function(a){var b=!1,c=function(a,c){setTimeout(function(){b?b=!1:(a.stopPropagation(),
window.location=c)},300)};Hammer(h,{prevent_default:!0,stop_browser_behavior:!0}).on("tap",function(b){c(b,a[0])});Hammer(h,{prevent_default:!0,stop_browser_behavior:!0}).on("doubletap",function(){b=!0})}(b),e.appendChild(h)):"undefined"!==typeof d.page&&(function(b){var c=!1,d=function(b,d){setTimeout(function(){c?c=!1:(b.stopPropagation(),a.onInternalLinkClick(d))},300)};Hammer(h,{prevent_default:!0,stop_browser_behavior:!0}).on("tap",function(a){d(a,b)});Hammer(h,{prevent_default:!0,stop_browser_behavior:!0}).on("doubletap",
function(){c=!0})}(d.page),e.appendChild(h));else if("video"==c){h.id="video."+d.id;if(d.showImage){var r=a.getVideoImageUrl(d.imageUri);(function(a){changeUrlWhenPubl(r,function(b){a.style.backgroundImage="url('"+b+"')";a.style.backgroundSize="cover";a.style.backgroundPosition="center"})})(h)}c=new Image;b*=d.height;b=50<b?50:0.8*b;c.src=a.videoPlayImage;h.appendChild(c);c.style.position="absolute";c.style.margin="auto";c.style.left="0";c.style.right="0";c.style.top="0";c.style.bottom="0";c.style.height=
b+"px";var s=!1,x=function(b){setTimeout(function(){s?s=!1:(b.stopPropagation(),a.onVideoClick(d))},300)};Hammer(h,{prevent_default:!0,stop_browser_behavior:!0}).on("tap",function(a){x(a)});Hammer(h,{prevent_default:!0,stop_browser_behavior:!0}).on("doubletap",function(){s=!0});e.appendChild(h)}else"cartItem"==c&&function(b,c,d,h){cart.getItems(function(g){g=g[0];var l=a.formCartItemOptions(b,g),k=new CartItemRender(b.id,c,d,h,l,e,cart);(function(b,c,d,C){c.div.style.pointerEvents="auto";var e=!1,
h=function(c){setTimeout(function(){e?e=!1:(c.stopPropagation(),a.onCartItemClick("Window"==d.onClickAction,b,C))},300)};Hammer(c.div,{prevent_default:!0,stop_browser_behavior:!0}).on("tap",function(a){h(a)});Hammer(c.div,{prevent_default:!0,stop_browser_behavior:!0}).on("doubletap",function(){e=!0});a.onNewCartItemRenderConstruction(c)})(b,k,l,g)},function(){throw"productsDB error";},b.id)}(d,k,g,b*l)}
function CartItemRender(c,d,e,b,a,l,k){this.itemID=c||NaN;c=18*b;var g=14*b,h=!1!==a.tagVisible,r=!1!==a.showTitle&&"string"===typeof a.title&&""!=a.title,s=12*b,x=5*b,q=5*b,m=r?0:3*b;e.x=Math.max(e.x,5*c);e.y=Math.max(e.y,3*c);var n=-1!=a.orientation.indexOf("top"),t=-1!=a.orientation.indexOf("left"),y=-1!=a.orientation.indexOf("bottom"),y=!n&&!y;l=el.createElement("div",{id:"cartItem-"+(1E3*Math.random()).toFixed(0),styles:{position:"absolute",cursor:"pointer",borderRadius:x+"px",fontFamily:"Arial",
textAlign:"center",color:a.priceColor}},l);d.applyAsPosition(l);d=new Vector2(c,y?m:c);var w=e.sub(new Vector2(d.x,d.y*(y?2:1)));w.applyAsSize(l);d.applyAsMargin(l,t,y?null:n);h&&(l.style.background="rgba("+fbUtils.hexToRGB(a.priceTagColor)+","+a.priceTagOpacity+")",e=el.createElement("p",{styles:{fontWeight:"bold",fontSize:g+"px",lineHeight:g+"px"}},null,{textContent:fbUtils.formatPrice(a.cost)}),r?(r=new Vector2(w.x-10*b,w.y-g-q),d=el.createElement("p",{styles:{fontSize:s+"px",lineHeight:s+"px",
width:r.x+"px"}},l,{textContent:a.title}),h=d.offsetHeight,q=el.createElement("p",{styles:{fontSize:s+"px",lineHeight:s+"px",marginLeft:5*b+"px",marginRight:5*b+"px",marginBottom:q+"px"}},l,{textContent:a.title}),h<r.y?(l.removeChild(d),s=(r.y-h)/2):(h=r.y-r.y%s,s=(r.y-h)/2,l.removeChild(d),q.style.maxWidth=r.x+"px",q.style.overflow="hidden",q.style.textOverflow="ellipsis",q.style.maxHeight=h+"px"),q.style.marginTop=s+"px"):(s=(w.y-g)/2,e.style.marginTop=s+"px"),e.style.marginBottom=s+"px",function(a,
b){a.style.maxWidth=w.x+"px";a.style.whiteSpace="nowrap";a.style.overflow="hidden";a.style.textOverflow="ellipsis"}(e,g),l.appendChild(e));b*=3;a=el.createElement("span",{styles:{position:"absolute",background:a.circleColor,borderRadius:c+"px",borderWidth:b+"px",borderColor:"white",borderStyle:"solid",color:a.basketColor,verticalAlign:"middle"}},l);g=(new Vector2(c,c)).mul(2);g.applyAsSize(a);s=g.x/2;a.style.lineHeight=g.x-2*b+"px";a.style.fontSize=s+"px";(new Vector2(-c,y?w.y/2-c:-c)).applyAsPosition(a,
t,y||n);this.updateQuantity=function(){var a=k.getItemQuantity(this.itemID);if("undefined"==typeof this.qty||this.qty!=a)this.qty=a,this.circleSpan.className=(0<a?"fullCartButtonInPage":"cartButtonInPage")+" cartIconShadow"};this.div=l;this.circleSpan=a;this.updateQuantity()}
function OnePage(c,d){function e(){var b;publicationData.shopInfo&&(window.cartRenders=[]);t?(f.div.parentNode&&f.div.parentNode.removeChild(f.div),q()):deleteAllChildren(f.div);f.loaded?((b=document.getElementById("stubPage"))&&c.contains(b)&&c.removeChild(b),f.vector&&parseVectorizedContentToDiv(f.vector,f.div,G),b=m().stretchToMe(f.publishedSize.proportions(),!0).x/f.publishedSize.x,sizeDiv(f.div,m().x,m().y),parseContentItems("link",publicationData.page[u].links,f.div,b),parseContentItems("video",
publicationData.page[u].videos,f.div,b),publicationData.shopInfo&&parseContentItems("cartItem",publicationData.page[u].shopItems,f.div,b,publicationData.getPageProperty(u,"contentScale")),s()):a()&&(b=document.getElementById("stubPage")||createDiv("stubPage"),sizeDiv(b,this.width,this.height),b.style.backgroundColor=publicationData.getPageProperty(u,"BGColor"),c.contains(b)||c.appendChild(b))}function b(b,c){if(u!=b)if(u&&a(u)&&!a(b)&&(f.image.style.visibility="visible"),u=b,fconsole.update("pos",
u),y||showPreloader(),a())f.loaded=!1,w||(f.image.style.visibility="hidden"),f.rasterSize.set(publicationData.getPageProperty(u,"width"),publicationData.getPageProperty(u,"height")),d(!0),e(),hidePreloader(),c&&c();else{f.vector=null;f.publishedSize=new Vector2(publicationData.getPageProperty(u,"width"),publicationData.getPageProperty(u,"height"));z.style.backgroundColor=publicationData.getPageProperty(u,"BGColor");L=publicationData.getPageProperty(u,"wide");var h;H&&(h="undefined"==typeof f.isWide||
f.isWide!=L,f.isWide=L,d(h));deleteAllChildren(f.div);loadManager.addPageToQueue({skipCurrentLoading:!0,image:f.image,quality:!0,position:u,onImageLoadComplete:function(){C=!0;f.loaded=!0;w&&A.createPattern(f.image,"no-repeat");var a=new Vector2(f.image.naturalWidth,f.image.naturalHeight);H||(h=f.rasterSize.x!=a.x||f.rasterSize.y!=a.y);f.rasterSize=a;H||d(h)},onPageLoadError:function(){f.loaded=!1},onAllIsComplete:function(a,b){f.vector=b;e();hidePreloader();c&&c()},onJSLoadComplete:function(){}})}}
function a(a){a=void 0!=a?a:u;return publicationData.getPageProperty(a,"stub")}function l(){D.width=this.width;D.height=this.height}function k(){if(f.loaded||a()){var b=D.width,c=D.height;if(C||F||I||J){A.clearRect(0,0,b,c);if(a())A.fillStyle=publicationData.getPageProperty(u,"BGColor"),A.fillRect(0,0,b,c);else{var d=f.image,e=E,B=G,M=Math.round(e.x),e=Math.round(e.y),h=0<M?0:Math.abs(M/B),g=0<e?0:Math.abs(e/B),b=Math.min(d.width*B,b)/B-h,c=Math.min(d.height*B,c)/B-g;(b||c)&&A.drawImage(d,M,e,d.width*
B,d.height*B);d=Math.round(E.x);B=Math.round(E.y);r(f.div,d,B,!1)}J=I=F=C=!1}}}function g(){sizeDiv(c,this.width,this.height)}function h(){if(I||C||J){var a=m(),b=function(a){return Math.floor(a)},c=a.stretchToMe(f.rasterSize.x/f.rasterSize.y,!0).map(b);c.applyAsSize(f.image);c.applyAsSize(f.div);b=a.getCenterPosition(c).map(b);b.applyAsPosition(f.image);b.applyAsPosition(f.div);a.applyAsSize(z);f.widthScale=a.x!==c.x?a.x:a.y;C=I=!1}if(F||J)a=Math.round(E.x),c=Math.round(E.y),r(z,a,c,!1),J=F=!1}function r(a,
b,c,d){d=d?"%":"px";a.style.left=b.toString()+d;a.style.top=c.toString()+d}function s(){search.active&&search.pages[u]?highlight.getHighlights(u,function(a){x();f.div.appendChild(K);parseContentItems("highlight",a,K,G)}):x()}function x(){deleteAllChildren(K);f.div.contains(K)&&f.div.removeChild(K)}function q(){f.div=createDiv("contentDiv");w?c.appendChild(f.div):(f.div.style.webkitTransform=null,z.appendChild(f.div))}function m(a){a=a||G;return(H?f.isWide?N:H:f.publishedSize).map(function(b){return Math.floor(b*
a)})}var n=window.system.platform.version,t="safari"==window.system.browser.name&&fbUtils.isArray(n)&&2<=n.length&&"4"==n[0]&&2<=n[1],y="safari"==window.system.browser.name&&fbUtils.isArray(n)&&3==n.length&&"4"==n[0]&&"0"==n[1]&&"4"==n[2],w=!1,z=createDiv("scrollDiv"),f={},D=document.createElement("canvas"),A=D.getContext("2d");f.loaded=!1;var C,E=new Vector2(0,0),G=0.1,F,I,J,u;f.rasterSize=new Vector2;f.publishedSize=new Vector2(100,100);var L;this.goToPage=function(a){b(a,function(){})};this.resize=
function(a,b){this.width=a;this.height=b;e();w?l():g()};this.setOffset=function(a,b){E.set(a);b||(F=!0)};this.getScale=function(){return G};this.setScale=function(a,b){G=a;b||(I=!0)};this.startPinchMode=function(){f.div.style.visibility="hidden";w||(this.pinchRedrawInterval=setInterval(function(){J=!0},1E3))};this.stopPinchMode=function(){e();this.pinchRedrawInterval&&(clearInterval(this.pinchRedrawInterval),this.pinchRedrawInterval=null);f.div.style.visibility="visible";I=F=!0};this.updateTopContent=
function(){e()};var K=createDiv("highlightContainer");this.setHighlight=function(a){a?s():(search.active=!1,x())};this.set=function(a,d){w?(c.style.overflow="visible",c.appendChild(D)):(c.style.position="absolute",z.style.webkitTransform=null,c.style.webkitTransform=null,c.style.overflow="hidden",c.appendChild(z));f.image=new Image;w||(f.image.style.webkitTransform=null,f.image.style.position="absolute",z.appendChild(f.image));q();b(a,d)};var H=publicationData.size&&publicationData.size.width&&publicationData.size.height?
new Vector2(publicationData.size.width,publicationData.size.height):null,N=H.vclone();N.x*=2;this.getScaledSize=m;this.getImageLoaded=function(){return f.loaded};this.isStub=function(){return a()};this.getOriginalSize=function(){return m(1)};this.drawFrame=w?k:h;this.getIsWide=function(){return L}}
function SimpleViewer(c){function d(){lastTime=(new Date).getTime();window.requestAnimFrame=window.requestAnimFrame||function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();(function C(){t.drawFrame();requestAnimFrame(C)})()}function e(a,b){a!=m&&(m=a,fconsole.update("scale",m),t.setScale(m,b),b||r())}function b(a,b){a.sub(q).vlength()&&
(q=a,t.setOffset(q,b))}function a(a,b){var c=new l(b);return a.clip(c.xmin,c.ymin,c.xmax,c.ymax)}function l(a){var b=t.getScaledSize(a).x;a=t.getScaledSize(a).y;var c=a>innerHeight;b>innerWidth?(this.xmax=0,this.xmin=innerWidth-b):this.xmax=this.xmin=innerWidth/2-b/2;c?(this.ymax=0,this.ymin=innerHeight-a):this.ymax=this.ymin=innerHeight/2-a/2}function k(c,d,f){var g=m;c=d&&h(n.map,m)!=n.defaultPos?n.defaultPos:h(n.map,m*(d?2:1))+(d?0:c?1:-1);c=Math.min(Math.max(c,0),n.map.length-1);c=n.map[c];f=
f?f:ALBUM?new Vector2(innerWidth/2,innerHeight/2):new Vector2(publicationData.rtlMode?innerWidth:0,0);g=q.sub(f.sub(q).mul(c/g-1));g=a(g,c);e(c);b(g);t.updateTopContent()}function g(c,d,f){var h,g=t.getOriginalSize(),l=(h="change"==c)&&d;d="resize"==c;c=n;if(l||d)c=determineScaleMap(g,t.getIsWide());g=m;if(l||h&&!D)g=c.map[c.defaultPos];var l=t.getScaledSize(g).x,k=t.getScaledSize(g).y,u=q.vclone();d?publicationData.rtlMode&&(u.x+=f):u.x=ALBUM?(innerWidth-l)/2:publicationData.rtlMode?innerWidth-l:
0;h&&(u.y=ALBUM?(innerHeight-k)/2:0);f=a(u,g);h=g;n=c;b(f);e(h);r()}function h(a,b){for(var c=0;c<a.length;c++){var d=a[c];if(0==c){if(b<=d||1==a.length)return 0}else{if(c==a.length-1)return a.length-1;if(b<a[c])return b<=(a[c-1]+a[c])/2?c-1:c;if(b<=(a[c]+a[c+1])/2)return c}}throw"determineScale abnormal return";}function r(){customEvents.fireEvent(ZOOM_LEVEL_CHANGED_FOR_WORKSPACE,{isSmallest:0==h(n.map,m),isLargest:h(n.map,m)==n.map.length-1})}function s(c,d,f){function e(a){a.ctrlKey&&(d.sendPinch&&
(d.startPinch&&d.startPinch(new Vector2(a.pageX,a.pageY)),d.sendPinch(s,new Vector2(0,0),new Vector2(a.pageX,a.pageY)),d.endPinch&&d.endPinch()),a.stopImmediatePropagation());a.altKey&&d.sendPinch&&(d.startPinch&&d.startPinch(new Vector2(a.pageX,a.pageY)),d.sendPinch(w,new Vector2(0,0),new Vector2(a.pageX,a.pageY)),d.endPinch&&d.endPinch());a.shiftKey&&d.handleDoubleClick(a);var b=a.currentTarget;if(Modernizr.touch){if(1<a.touches.length){g(a);return}b.addEventListener(DOWN_EVENT,g,!1)}b.removeEventListener(DOWN_EVENT,
e,!1);b.addEventListener(MOVE_EVENT,h,!1);b.addEventListener(UP_EVENT,k,!1);b.addEventListener("touchcancel",k,!1);b.addEventListener("mouseout",k,!1);a=a.touches?a.touches[0]:a;b.pos=new Vector2(a.pageX,a.pageY);r()}function h(c){c.preventDefault();var d=c.touches?c.touches[0]:c,d=new Vector2(d.pageX,d.pageY),e=c.currentTarget.pos;c.currentTarget.pos=d;c=d.sub(e);p.dv0x=p.dv0x||c.x;if(p.timeStamp){d=(new Date).getTime();e=d-p.timeStamp;p.vDiff=p.vDiff.add(c);p.moveTime+=e;p.timeStamp=d;p.trackLength+=
Math.abs(c.x);p.movePath.push({dv:c,time:e});d=t.getScaledSize(void 0).x<=innerWidth||t.isStub();f&&(e=p.vDiff.y?Math.abs(p.vDiff.x)/Math.abs(p.vDiff.y):1E10,Math.abs(p.vDiff.x)>y/1.5*(1.5-e)?p.horizontalAllowed=!0:!p.vDiff.y||1.5<e||p.horizontalAllowed||(c.x=0));if(1E3<p.moveTime||p.dv0x&&c.x&&p.dv0x/Math.abs(p.dv0x)!=c.x/Math.abs(c.x))p.slideDisabledThisTime=!0;!p.slideDisabledThisTime&&p.vDiff.x&&0.5>Math.abs(p.vDiff.y)/Math.abs(p.vDiff.x)&&(c.y=0);if(d&&!p.slideDisabledThisTime&&4<p.trackLength&&
75<p.moveTime){for(var g=p.movePath,d=t.getScaledSize(void 0).y>innerHeight,A,k,l,m=l=k=e=A=0;m<g.length;m++){var n=g[m];A+=n.dv.x;e+=n.dv.y;k+=Math.abs(n.dv.x);l+=n.time}g=Math.abs(A);k=Math.abs(k-g);A=0>A;14>k&&7<g&&(!d&&1>=Math.abs(e)/g||d&&g>7+200*Math.abs(e)/g&&g>0.2*l)?(flipPage(A),d=!0):d=!1;d&&(p.slideDisabledThisTime=!0)}}(c.x||c.y)&&b(a(q.add(c)))}function g(a){if(1<a.touches.length){var b=a.currentTarget,c=a.touches[0];a=a.touches[1];b.pos=new Vector2((c.pageX+a.pageX)/2,(c.pageY+a.pageY)/
2);b.startDist=x(c,a);b.removeEventListener(UP_EVENT,k,!1);b.removeEventListener("touchcancel",k,!1);b.removeEventListener(MOVE_EVENT,h,!1);b.removeEventListener(DOWN_EVENT,g,!1);b.addEventListener(MOVE_EVENT,l,!1);b.addEventListener(UP_EVENT,m,!1);b.addEventListener("touchcancel",m,!1);d.startPinch&&d.startPinch(b.pos)}}function l(a){a.preventDefault();if(1<a.touches.length){var b=a.currentTarget,c=a.touches[0],e=a.touches[1];a=x(c,e);var c=new Vector2((c.pageX+e.pageX)/2,(c.pageY+e.pageY)/2),e=
a/b.startDist,f=c.sub(b.pos);d.sendPinch(e,f,c);b.startDist=a;b.pos=c}}function m(a){var b=a.currentTarget,c=a.touches.length;if(0<c){b.removeEventListener(MOVE_EVENT,l,!1);b.removeEventListener(UP_EVENT,m,!1);b.removeEventListener("touchcancel",m,!1);b.addEventListener(MOVE_EVENT,h,!1);b.addEventListener(UP_EVENT,k,!1);b.addEventListener("touchcancel",k,!1);var e=a.touches?a.touches[0]:a;b.pos=new Vector2(e.pageX,e.pageY);r()}d.endPinch&&d.endPinch();0==c&&k(a)}function n(a){p.timeoutID||(p.timeoutID=
setTimeout(function(){p.horizontalAllowed=!1;p.timeoutID=null},a))}function k(a){var b=a.currentTarget;Modernizr.touch&&a.touches&&0!=a.touches.length||(b.removeEventListener(MOVE_EVENT,h,!1),b.removeEventListener(UP_EVENT,k,!1),b.removeEventListener("touchcancel",k,!1),b.removeEventListener("mouseout",k,!1),b.addEventListener(DOWN_EVENT,e,!1));p.xDiff=0;p.yDiff=0;n(z)}function r(){p.timeStamp=(new Date).getTime();p.moveTime=0;p.movePath=[];p.trackLength=0;p.slideDisabledThisTime=!1;p.dv0x=0;p.vDiff.set(0,
0)}var s=1.15,w=0.8,y=innerWidth/4,z=1250;c.addEventListener(DOWN_EVENT,e,!1);var p={};p.vDiff=new Vector2(0,0)}function x(a,b){var c=a.pageX-b.pageX,d=a.pageY-b.pageY;return Math.sqrt(c*c+d*d)}var q=new Vector2(0,0),m=0.1,n,t=new OnePage(c,function(a){g("change",a)});this.goToPage=function(a){t.goToPage(a)};var y=this;setInterval(function(){y.width==innerWidth&&y.height==innerHeight||y.resize()},500);this.resize=function(){var a=innerWidth-this.width;this.width=innerWidth;this.height=innerHeight;
t.getImageLoaded()&&g("resize",!1,a);t.resize()};var w,z=function(){var a=document.createElement("p");a.style.opacity="0.7";a.style.backgroundColor="#e0efee";a.style.color="#11111f";a.style.fontSize="18px";a.style.zIndex=1E3;a.style.position="absolute";this.element=a};z.prototype.setText=function(a){this.element.innerText=a};z.prototype.positionMe=function(a){this.element.style.left=px(a.x-this.element.offsetWidth/2);this.element.style.top=px(a.y-this.element.offsetHeight/2)};var f=new z;this.startPinch=
function(a){c.appendChild(f.element);f.positionMe(a);w?(clearTimeout(w),w=null):t.startPinchMode()};this.endPinch=function(){c.removeChild(f.element);w=setTimeout(function(){t.stopPinchMode();w=null;r()},t.isStub()?0:500)};this.sendPinch=function(c,d,g){m*c<n.map[0]?c=n.map[0]/m:m*c>n.map[n.map.length-1]&&(c=n.map[n.map.length-1]/m);d=d.add(g.sub(q).mul(1-c));d=q.add(d);c*=m;d=a(d,c);e(c,!0);b(d,!0);f.setText(window.LOCALS.ZOOM+" "+(100*m).toFixed(0)+"%");f.positionMe(g)};this.incZoom=function(){k(!0)};
this.decZoom=function(){k(!1)};this.setHighlight=function(a){t.setHighlight(a)};var D=getKeepZoomScaleWhileFlipping(publicationData.type);this.set=function(a,b){setElementPosition(c,{left:0,top:0});t.set(a,b);this.resize();d();s(c,this,publicationData.type!=PT_PHOTOALBUM)};this.handleDoubleClick=function(a){a=a.touches?a.touches[0]:a;a=new Vector2(a.pageX,a.pageY);k(!0,!0,a)}};
