(function(f){String.prototype.format=String.prototype.format||function(){var a=RegExp("(%(.+?)%)","g");return function(b){return this.replace(a,function(a,d,c){return c in b?b[c]:d})}}();var c=function(a){a=a||{};this.requiredVersion=a.requiredVersion||"11.3.0";this.title=a.title||"Adobe Flash Player Update required!";this.description=a.description||"This installation will only take a few moments. Using the current version may cause performance problems and publication errors.";this.updateUrl=a.updateUrl||
"http://get.adobe.com/flashplayer/";this.buttonSrc=a.buttonSrc||"files/flash/160x41_Get_Flash_Player.jpg";this.mbClass=a.mbClass||"flash-notification";this.cookieName=a.cookieName||"flippingbook-flash_version_checked";this.parentElem=a.parentElem||document.getElementById("container");this.box=null;this.boxStyle=a.boxStyle||"margin:3px;padding:12px 24px 12px 12px;overflow:hidden;background:#f9f6c4;border:1px solid #bab893;-webkit-border-radius:7px;-moz-border-radius:7px;border-radius:7px;font:11px/14px Arial;position: relative;";
this.titleStyle=a.titleStyle||"font-weight:bold;padding-top:2px;padding-bottom:4px;";this.closeButtonStyle=a.closeButtonStyle||"display:block;width:8px;height:8px;text-decoration:none;font:0/0 a;cursor:pointer;background:url('files/flash/close.png');position:absolute;top:12px;right:12px;left:auto;bottom:auto;";this.downloadButtonStyle=a.downloadButtonStyle||"display:block;float:left;text-decoration:none;position:absolute;top:50%;left:12px;margin-top:-20px;";this.rightColStyle=a.rightColStyle||"margin-left: 170px;";
this.tpl=a.tpl||'<a href="javascript:void(0)" style="%closeButtonStyle%"></a><a href="%updateUrl%" style="%downloadButtonStyle%" target="_blank"><img src="%buttonSrc%" alt="" border="0" style="border:0;display:block;" width="160" height="41"/></a><div style="%rightColStyle%"><div style="%titleStyle%">%title%</div><div>%description%</div></div>';this.onShow=a.onShow||function(){};this.onClose=a.onClose||function(a){a.style.display="none"};if(this.needPpWarning=this._needPpWarning())this.title=this.ppTitle||
"This publication cannot be viewed locally with Google Chrome!",this.description=this.ppDescription||"If you want to open this publication, please upload it to a web-server or use an offline version.",this.updateUrl="#",this.buttonSrc="files/flash/offline.png",this.tpl=a.tpl||'<a href="javascript:void(0)" style="%closeButtonStyle%"></a><a href="%updateUrl%" style="%downloadButtonStyle%" target="_blank"><img src="%buttonSrc%" alt="" border="0" style="border:0;display:block;"  height="40"/></a><div style="%rightColStyle%"><div style="%titleStyle%">%title%</div><div >%description%</div></div>',
this.rightColStyle=a.rightColStyle||"margin-left: 55px;";this.init()};c.prototype.init=function(){this.requiredVersion=this.requiredVersion.split(".");(this.userVersion=this.userPlayerVersion()||!1)&&this.userVersion.length&&this.showMessageBox()};c.prototype.userPlayerVersion=function(){navigator.userAgent.toLowerCase();navigator.platform.toLowerCase();var a=[0,0,0],b=null;if("undefined"!=typeof navigator.plugins&&"object"==typeof navigator.plugins["Shockwave Flash"]){if((b=navigator.plugins["Shockwave Flash"].description)&&
!("undefined"!=typeof navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&!navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin))b=b.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),a[0]=parseInt(b.replace(/^(.*)\..*$/,"$1"),10),a[1]=parseInt(b.replace(/^.*\.(.*)\s.*$/,"$1"),10),a[2]=/[a-zA-Z]/.test(b)?parseInt(b.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if("undefined"!=typeof f.ActiveXObject)try{var c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(c&&(b=c.GetVariable("$version")))b=
b.split(" ")[1].split(","),a=[parseInt(b[0],10),parseInt(b[1],10),parseInt(b[2],10)]}catch(d){}return a};c.prototype.createMessageBox=function(){var a=this,b=document.createElement("DIV");b.setAttribute("id",this.mbClass);b.setAttribute("class",this.mbClass);b.style.cssText=this.boxStyle;b.innerHTML=this.tpl.format({title:this.title,description:this.description,updateUrl:this.updateUrl,buttonSrc:this.buttonSrc,titleStyle:this.titleStyle,closeButtonStyle:this.closeButtonStyle,downloadButtonStyle:this.downloadButtonStyle,
rightColStyle:this.rightColStyle});b.getElementsByTagName("a")[0].onclick=function(){a.onClose(b)};return b};c.prototype.showMessageBox=function(){if(!(this.cookie(this.cookieName)||!this.pluginIsOutOfDate()&&!this.needPpWarning)){var a=new Date,a=(new Date(a.setTime(a.getTime()+12096E5))).toGMTString();this.cookie(this.cookieName,!0,a);this.box=this.createMessageBox();this.parentElem.childNodes.length?this.parentElem.insertBefore(this.box,this.parentElem.childNodes[0]):this.parentElem.appendChild(this.box);
this.onShow()}};c.prototype.cookie=function(a,b,c,d,f,g){if(1==arguments.length&&"string"==typeof a){var e=document.cookie.match("(^|;) ?"+a+"=([^;]*)(;|$)");return e?decodeURI(e[2]):null}if(2==arguments.length&&"string"==typeof a&&null===b)return e=new Date,e.setTime(e.getTime()-1),document.cookie=a+="=; expires="+e.toGMTString(),null;e=a+"="+encodeURI(b)+(c?"; expires="+c:"")+(d?"; path="+d:"")+(f?"; domain="+f:"")+(g?"; secure":"");return document.cookie=e};c.prototype.pluginIsOutOfDate=function(){return 0<=
function(a,b){if(a===b)return 0;for(var c=Math.min(a.length,b.length),d=0;d<c;d++){if(parseInt(a[d])>parseInt(b[d]))return 1;if(parseInt(a[d])<parseInt(b[d]))return-1}return a.length>b.length?1:a.length<b.length?-1:0}(this.userVersion,this.requiredVersion)?!1:!0};c.prototype.isPPAPI=function(){var a=!1,b=navigator.mimeTypes;if(b&&b["application/x-shockwave-flash"]&&b["application/x-shockwave-flash"].enabledPlugin&&("pepflashplayer.dll"==b["application/x-shockwave-flash"].enabledPlugin.filename||"libpepflashplayer.so"==
b["application/x-shockwave-flash"].enabledPlugin.filename||-1!==b["application/x-shockwave-flash"].enabledPlugin.filename.indexOf("Chrome.plugin",b["application/x-shockwave-flash"].enabledPlugin.filename.length-13)))a=!0;return a};c.prototype._needPpWarning=function(){var a=0<=navigator.userAgent.indexOf("Chrome"),b="file:"==f.location.protocol;return a&&b&&this.isPPAPI()};f.CheckFlash=c})(window);
