function Detect(){playerVersion=[0,0,0];this.ua=navigator.userAgent.toLowerCase();var a=navigator.platform.toLowerCase(),b=this.ua.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||[null,"unknown",0];if("undefined"!=typeof navigator.plugins&&"object"==typeof navigator.plugins["Shockwave Flash"]){if((d=navigator.plugins["Shockwave Flash"].description)&&!("undefined"!=typeof navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&
!navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin))plugin=!0,ie=!1,d=d.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),playerVersion[0]=parseInt(d.replace(/^(.*)\..*$/,"$1"),10),playerVersion[1]=parseInt(d.replace(/^.*\.(.*)\s.*$/,"$1"),10),playerVersion[2]=/[a-zA-Z]/.test(d)?parseInt(d.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if("undefined"!=typeof window.ActiveXObject)try{var c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(c&&(d=c.GetVariable("$version")))ie=!0,d=d.split(" ")[1].split(","),
playerVersion=[parseInt(d[0],10),parseInt(d[1],10),parseInt(d[2],10)]}catch(e){}this.flash=0===playerVersion[0]&&0===playerVersion[1]&&0===playerVersion[2]?!1:!0;this.flashVer=playerVersion[0]+"."+playerVersion[1]+"."+playerVersion[2];this.browser={};this.platform={};this.device={};this.browser.name="version"==b[1]?b[3]:b[1];this.browser[this.browser.name]=!0;mode="ie"==b[1]&&document.documentMode;this.browser.version=mode||parseFloat("opera"==b[1]&&b[4]?b[4]:b[2]);this.platform.name=this.ua.match(/ip(?:ad|od|hone)/)?
"ios":this.ua.match(/(?:msie 9)/)?"wphone":(this.ua.match(/(?:webos|android|bada|symbian|palm|blackberry)/)||a.match(/mac|win|linux/)||["other"])[0];this.platform[this.platform.name]=!0;this.platform.mac&&(this.browser.safari||this.browser.chrome?this.platform.version=this.ua.match(/10_\d*/)[0].split("_"):this.browser.firefox?this.platform.version=this.ua.match(/10\.\d*/)[0].split("."):this.browser.opera&&(this.platform.version=this.ua.match(/10\.\d*/)[0].split(".")));this.device.name=this.ua.match(/ipad/)?
"ipad":this.ua.match(/ipad/)?"ipad":this.ua.match(/iphone/)?"iphone":this.ua.match(/android/)?"android":this.ua.match(/silk/)?"silk":this.ua.match(/kindle/)?"kindle":a.match(/mac|win|linux/)?"pc":"other";this.device[this.device.name]=!0;this.device.version="android"===this.device.name&&this.ua.match(/android 2/)?2:"android"===this.device.name&&this.ua.match(/android 3/)?3:"android"===this.device.name&&this.ua.match(/android 4/)?4:0;this.isBasic=this.isFlash=this.isMobile=!1;"silk"==this.device.name||
"kindle"==this.device.name?this.isMobile=!0:this.platform.ios||this.platform.blackberry?this.isMobile=!0:(this.platform.ios||this.platform.android)&&(this.browser.safari||this.browser.chrome)?this.isMobile=!0:this.platform.android?this.isBasic=!0:(this.device.pc||this.device.other)&&!this.flash?this.isBasic=!0:this.isFlash=!0;this.isTablet="ipad"==this.device.name||3==this.device.version?!0:!1}var browser=new Detect;
if(browser.isMobile){var page=getParameterByName("p")||getParameterByName("page"),productID=getParameterByName("id"),page=page?"#"+page:window.location.hash,page=productID?page+"/"+productID:page;window.location="./"+mobileFolder+"/index.html"+page}function getParameterByName(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(window.location.href);return null==a?"":a[1]}
function checkPage(){var a="",a=getParameterByName("p")||getParameterByName("page"),b=getParameterByName("z")||getParameterByName("zoomed"),c=getParameterByName("id");if(a)a="#"+a,b&&(a+="/z"),c&&(a+="/"+c),b=window.location.href,window.location.replace(b.substring(0,b.indexOf("?"))+a)}var MAXIMUM_SIZE=35,MINIMUM_SIZE=5,BOUND_SIZE=14,knownDevices=[{name:"gt-p1000",size:17.5}];
function getScreenSize(){var a=null,b=navigator.userAgent.toLowerCase();knownDevices.forEach(function(c){-1!=b.indexOf(c.name)&&(a=c)});if(null!=a)return a.size;if("undefined"!=typeof Storage&&localStorage.getItem("detectedDisplaySize"))return parseFloat(localStorage.getItem("detectedDisplaySize"))}
function checkViewportSize(a,b){setTimeout(function(){var c=2.54*(Math.sqrt(Math.pow(innerWidth,2)+Math.pow(innerHeight,2))/100);b&&b();if("undefined"!=typeof Storage)localStorage.detectedDisplaySize=c;a(c)},200)}function isViewportCheckNeeded(){var a=!1,b=navigator.userAgent.toLowerCase();knownDevices.forEach(function(c){-1!=b.indexOf(c.name)&&(a=!0)});return!a&&("undefined"==typeof Storage||!localStorage.getItem("detectedDisplaySize"))}
function afterLoad(){if(browser.isMobile){document.body.style.visibility="hidden";var a=parseInt(window.location.hash.substring(2,window.location.hash.length-1));window.location="./"+mobileFolder+"/index.html"+(a?"#"+a:"")}else checkPage(),(!browser.platform.mac||!browser.browser.chrome)&&setFocusOnFlash()}function setFocusOnFlash(){var a=swfobject.getObjectById("flashbook");if(a)a.tabIndex=0,a.focus()}
function getURLParam(){var a={},b=window.location.href;if(-1<b.indexOf("?"))for(var b=b.substr(b.indexOf("?")).split("&"),c=0;c<b.length;c++){var e=b[c].split("=");a[e[0]]=e[1]}a.assets=assetsFolder;return a}
if(!browser.isMobile){var dir="./"+filesFolderName+"/",getURI=function(){var a=document.location.href.split("/");a.length-=1;var a=a.join("/"),b=dir.split("/");b[0]="."==b[0]?"":b[0];b=b.join("/");return a+b},swfName="preloader.swf?rnd="+projectGUID,flashvars=getURLParam(),params={baseURI:getURI(),base:dir,allowFullScreen:!0,allowScriptAccess:"always",quality:"high",scale:"noscale",bgcolor:documentBackColor,allowFullScreenInteractive:!0},attributes={align:"middle"};swfobject.embedSWF(dir+swfName,
"flashbook","100%","100%","10.3.0",dir+"expressInstall.swf",flashvars,params,attributes,outputStatus)}document.addEventListener?document.addEventListener("DOMContentLoaded",afterLoad):document.attachEvent("onreadystatechange",afterLoad);
